export const EnrollData = [
    {
        id: 1,
        StudentId:'LMS001',
        FullName:"Surya Kumar",
        MobileNumber:"98733 88573",
        Email:"surya@gmail.com",
        City:"Pollachi",
        PaymentMode:"Cash",
    },
    {
        id: 2,
        StudentId:'LMS002',
        FullName:"Karthi",
        MobileNumber:"88733 99573",
        Email:"karthi55@gmail.com",
        City:"Selam",
        PaymentMode:"Card",
    },
    {
        id: 3,
        StudentId:'LMS003',
        FullName:"Vijay Kumar",
        MobileNumber:"98824 24537",
        Email:"vijay@gmail.com",
        City:"Salem",
        PaymentMode:"OnlineTransfer",
    },
    {
        id: 4,
        StudentId:'LMS004',
        FullName:"Deva Rajan",
        MobileNumber:"73294 09183",
        Email:"deva@gmail.com",
        City:"Coimabatore",
        PaymentMode:"Cash",
    },
    {
        id: 5,
        StudentId:'LMS005',
        FullName:"Jhonsi Suzi",
        MobileNumber:"99521 75120",
        Email:"suzi@gmail.com",
        City:"Chennai",
        PaymentMode:"Online Transfer",
    },
    {
        id: 6,
        StudentId:'LMS006',
        FullName:"Laskhmi",
        MobileNumber:"91710 88573",
        Email:"lakshmi@gmail.com",
        City:"Banglore",
        PaymentMode:"Card",
    },
    {
        id: 7,
        StudentId:'LMS008',
        FullName:"Vishnu",
        MobileNumber:"9710 88573",
        Email:"vitchu@gmail.com",
        City:"Chennai",
        PaymentMode:"Cash",
    },
]