export const courseRow = [
    {
        id: 1,
        CourseId:'01JFD01',
        CourseName:"Java FullStack Development",
        avatar:"https://thumbs.dreamstime.com/b/java-programming-concept-virtual-machine-server-room-background-java-programming-concept-virtual-machine-server-room-148684554.jpg",
        Description:"Learning Java and Advanced Java",
        MainModules:"5",
        ElectiveModules:"7",
        Duration:"12 Months",
    },
    {
        id: 2,
        CourseId:'02PFD02',
        CourseName:"Python FullStack Development",
        avatar:"https://res.cloudinary.com/dyd911kmh/image/upload/v1646560927/shutterstock_1329434768_bf9003ea47.jpg",
        Description:"Learning Python and Django, Flask",
        MainModules:"3",
        ElectiveModules:"5",
        Duration:"6 Months",
    },
    {
        id: 3,
        CourseId:'03MRFD03',
        CourseName:"MERN FullStack Development",
        avatar:"https://e1.pxfuel.com/desktop-wallpaper/944/771/desktop-wallpaper-create-a-full-stack-web-app-on-reactjs-and-nodejs-by-saad-khan6670-mern-stack-thumbnail.jpg",
        Description:"Learning React and NodeJS, Express",
        MainModules:"4",
        ElectiveModules:"5",
        Duration:"3 Months",
    },
    {
        id: 4,
        CourseId:'04MAFD01',
        CourseName:"MEAN FullStack Development",
        avatar:"https://www.weblineindia.com/wp-content/uploads/2016/12/mean-stack-1.jpg",
        Description:"Learning Angular and NodeJS, Express",
        MainModules:"4",
        ElectiveModules:"5",
        Duration:"3 Months",
    },
    {
        id: 5,
        CourseId:'01JFD01',
        CourseName:"Java FullStack Development",
        avatar:"https://thumbs.dreamstime.com/b/java-programming-concept-virtual-machine-server-room-background-java-programming-concept-virtual-machine-server-room-148684554.jpg",
        Description:"Learning Java and Advanced Java",
        MainModules:"5",
        ElectiveModules:"7",
        Duration:"12 Months",
    },
    {
        id: 6,
        CourseId:'02PFD02',
        CourseName:"Python FullStack Development",
        avatar:"https://res.cloudinary.com/dyd911kmh/image/upload/v1646560927/shutterstock_1329434768_bf9003ea47.jpg",
        Description:"Learning Python and Django, Flask",
        MainModules:"3",
        ElectiveModules:"5",
        Duration:"6 Months",
    },
    {
        id: 7,
        CourseId:'03MRFD03',
        CourseName:"MERN FullStack Development",
        avatar:"https://e1.pxfuel.com/desktop-wallpaper/944/771/desktop-wallpaper-create-a-full-stack-web-app-on-reactjs-and-nodejs-by-saad-khan6670-mern-stack-thumbnail.jpg",
        Description:"Learning React and NodeJS, Express",
        MainModules:"4",
        ElectiveModules:"5",
        Duration:"3 Months",
    },
    {
        id: 8,
        CourseId:'04MAFD01',
        CourseName:"MEAN FullStack Development",
        avatar:"https://www.weblineindia.com/wp-content/uploads/2016/12/mean-stack-1.jpg",
        Description:"Learning Angular and NodeJS, Express",
        MainModules:"4",
        ElectiveModules:"5",
        Duration:"3 Months",
    },
        
]